
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - clusterip.allocator.x-k8s.io
  resources:
  - ipranges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterip.allocator.x-k8s.io
  resources:
  - ipranges/status
  verbs:
  - get
  - patch
  - update
